import mongoose from "mongoose";

const aiMaterialSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
  },
  type: {
    type: String,
    required: true,
    enum: ["notes", "code-guide", "mcq"],
  },
  category: {
    type: String,
    required: true,
    enum: ["Theory", "Lab"],
  },
  content: {
    type: String,
    required: true, // Markdown content generated by AI
  },
  course: {
    type: String,
    required: true,
  },
  week: {
    type: Number,
    required: true,
  },
  topic: {
    type: String,
    required: true,
  },
  sourceMaterialId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Material",
    required: true,
  },
  customization: {
    type: String,
  },
  uploadedBy: {
    type: String, // Clerk User ID
    required: true,
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

const AiMaterial = mongoose.models.AiMaterial || mongoose.model("AiMaterial", aiMaterialSchema);

// If the model already exists, we need to ensure the schema is updated
if (mongoose.models.AiMaterial) {
  // Check if the enum needs updating
  const typePath = mongoose.models.AiMaterial.schema.path('type');
  if (typePath.enumValues && !typePath.enumValues.includes('mcq')) {
    // This is a workaround for development hot-reloading
    mongoose.deleteModel('AiMaterial');
    // Re-register
    mongoose.model("AiMaterial", aiMaterialSchema);
  }
}

export default mongoose.models.AiMaterial || mongoose.model("AiMaterial", aiMaterialSchema);
